name: Test CDK Demos Pipeline
on:
  push:
    branches: ["**"]
    paths: ["demos-pipeline/**"]
  pull_request:
    branches: [master]
    paths: ["demos-pipeline/**"]
jobs:
  Run-CDK-Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        dir: ['demos-pipeline/lib', 'demos-pipeline/example']

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run check
      - run: npm run build --if-present
      - name: Test ${{ matrix.dir }}
        run: npm test
